// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/search/proto/search.proto

package search

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NearbyRequest struct {
	Lat                  float32  `protobuf:"fixed32,1,opt,name=lat" json:"lat,omitempty"`
	Lon                  float32  `protobuf:"fixed32,2,opt,name=lon" json:"lon,omitempty"`
	InDate               string   `protobuf:"bytes,3,opt,name=inDate" json:"inDate,omitempty"`
	OutDate              string   `protobuf:"bytes,4,opt,name=outDate" json:"outDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NearbyRequest) Reset()         { *m = NearbyRequest{} }
func (m *NearbyRequest) String() string { return proto.CompactTextString(m) }
func (*NearbyRequest) ProtoMessage()    {}
func (*NearbyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_22ef3362cb153859, []int{0}
}
func (m *NearbyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NearbyRequest.Unmarshal(m, b)
}
func (m *NearbyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NearbyRequest.Marshal(b, m, deterministic)
}
func (dst *NearbyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NearbyRequest.Merge(dst, src)
}
func (m *NearbyRequest) XXX_Size() int {
	return xxx_messageInfo_NearbyRequest.Size(m)
}
func (m *NearbyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NearbyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NearbyRequest proto.InternalMessageInfo

func (m *NearbyRequest) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *NearbyRequest) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *NearbyRequest) GetInDate() string {
	if m != nil {
		return m.InDate
	}
	return ""
}

func (m *NearbyRequest) GetOutDate() string {
	if m != nil {
		return m.OutDate
	}
	return ""
}

type SearchResult struct {
	PubIds               []string `protobuf:"bytes,1,rep,name=pubIds" json:"pubIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResult) Reset()         { *m = SearchResult{} }
func (m *SearchResult) String() string { return proto.CompactTextString(m) }
func (*SearchResult) ProtoMessage()    {}
func (*SearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_22ef3362cb153859, []int{1}
}
func (m *SearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResult.Unmarshal(m, b)
}
func (m *SearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResult.Marshal(b, m, deterministic)
}
func (dst *SearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResult.Merge(dst, src)
}
func (m *SearchResult) XXX_Size() int {
	return xxx_messageInfo_SearchResult.Size(m)
}
func (m *SearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResult proto.InternalMessageInfo

func (m *SearchResult) GetPubIds() []string {
	if m != nil {
		return m.PubIds
	}
	return nil
}

func init() {
	proto.RegisterType((*NearbyRequest)(nil), "search.NearbyRequest")
	proto.RegisterType((*SearchResult)(nil), "search.SearchResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SearchClient is the client API for Search service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchClient interface {
	Nearby(ctx context.Context, in *NearbyRequest, opts ...grpc.CallOption) (*SearchResult, error)
}

type searchClient struct {
	cc *grpc.ClientConn
}

func NewSearchClient(cc *grpc.ClientConn) SearchClient {
	return &searchClient{cc}
}

func (c *searchClient) Nearby(ctx context.Context, in *NearbyRequest, opts ...grpc.CallOption) (*SearchResult, error) {
	out := new(SearchResult)
	err := c.cc.Invoke(ctx, "/search.Search/Nearby", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServer is the server API for Search service.
type SearchServer interface {
	Nearby(context.Context, *NearbyRequest) (*SearchResult, error)
}

func RegisterSearchServer(s *grpc.Server, srv SearchServer) {
	s.RegisterService(&_Search_serviceDesc, srv)
}

func _Search_Nearby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NearbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).Nearby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.Search/Nearby",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).Nearby(ctx, req.(*NearbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Search_serviceDesc = grpc.ServiceDesc{
	ServiceName: "search.Search",
	HandlerType: (*SearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Nearby",
			Handler:    _Search_Nearby_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/search/proto/search.proto",
}

func init() {
	proto.RegisterFile("services/search/proto/search.proto", fileDescriptor_search_22ef3362cb153859)
}

var fileDescriptor_search_22ef3362cb153859 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2a, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x2d, 0xd6, 0x2f, 0x4e, 0x4d, 0x2c, 0x4a, 0xce, 0xd0, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x87, 0x72, 0xf4, 0xc0, 0x1c, 0x21, 0x36, 0x08, 0x4f, 0x29, 0x95, 0x8b, 0xd7, 0x2f, 0x35,
	0xb1, 0x28, 0xa9, 0x32, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x80, 0x8b, 0x39, 0x27,
	0xb1, 0x44, 0x82, 0x51, 0x81, 0x51, 0x83, 0x29, 0x08, 0xc4, 0x04, 0x8b, 0xe4, 0xe7, 0x49, 0x30,
	0x41, 0x45, 0xf2, 0xf3, 0x84, 0xc4, 0xb8, 0xd8, 0x32, 0xf3, 0x5c, 0x12, 0x4b, 0x52, 0x25, 0x98,
	0x15, 0x18, 0x35, 0x38, 0x83, 0xa0, 0x3c, 0x21, 0x09, 0x2e, 0xf6, 0xfc, 0xd2, 0x12, 0xb0, 0x04,
	0x0b, 0x58, 0x02, 0xc6, 0x55, 0x52, 0xe3, 0xe2, 0x09, 0x06, 0x5b, 0x18, 0x94, 0x5a, 0x5c, 0x9a,
	0x53, 0x02, 0x32, 0xa1, 0xa0, 0x34, 0xc9, 0x33, 0xa5, 0x58, 0x82, 0x51, 0x81, 0x19, 0x64, 0x02,
	0x84, 0x67, 0x64, 0xcf, 0xc5, 0x06, 0x51, 0x27, 0x64, 0xca, 0xc5, 0x06, 0x71, 0x98, 0x90, 0xa8,
	0x1e, 0xd4, 0xe5, 0x28, 0x0e, 0x95, 0x12, 0x81, 0x09, 0x23, 0x1b, 0x9c, 0xc4, 0x06, 0xf6, 0x9e,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x94, 0xc3, 0x00, 0x82, 0x04, 0x01, 0x00, 0x00,
}
