// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/profile/proto/profile.proto

package profile

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	PubIds               []string `protobuf:"bytes,1,rep,name=pubIds" json:"pubIds,omitempty"`
	Locale               string   `protobuf:"bytes,2,opt,name=locale" json:"locale,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_profile_86ea0ebb379f6dd7, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPubIds() []string {
	if m != nil {
		return m.PubIds
	}
	return nil
}

func (m *Request) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

type Result struct {
	Pubs                 []*Pub   `protobuf:"bytes,1,rep,name=pubs" json:"pubs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_profile_86ea0ebb379f6dd7, []int{1}
}
func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (dst *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(dst, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetPubs() []*Pub {
	if m != nil {
		return m.Pubs
	}
	return nil
}

type Pub struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phoneNumber" json:"phoneNumber,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Address              *Address `protobuf:"bytes,5,opt,name=address" json:"address,omitempty"`
	Images               []*Image `protobuf:"bytes,6,rep,name=images" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pub) Reset()         { *m = Pub{} }
func (m *Pub) String() string { return proto.CompactTextString(m) }
func (*Pub) ProtoMessage()    {}
func (*Pub) Descriptor() ([]byte, []int) {
	return fileDescriptor_profile_86ea0ebb379f6dd7, []int{2}
}
func (m *Pub) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pub.Unmarshal(m, b)
}
func (m *Pub) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pub.Marshal(b, m, deterministic)
}
func (dst *Pub) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pub.Merge(dst, src)
}
func (m *Pub) XXX_Size() int {
	return xxx_messageInfo_Pub.Size(m)
}
func (m *Pub) XXX_DiscardUnknown() {
	xxx_messageInfo_Pub.DiscardUnknown(m)
}

var xxx_messageInfo_Pub proto.InternalMessageInfo

func (m *Pub) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Pub) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pub) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Pub) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Pub) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Pub) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

type Address struct {
	StreetNumber         string   `protobuf:"bytes,1,opt,name=streetNumber" json:"streetNumber,omitempty"`
	StreetName           string   `protobuf:"bytes,2,opt,name=streetName" json:"streetName,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city" json:"city,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=state" json:"state,omitempty"`
	Country              string   `protobuf:"bytes,5,opt,name=country" json:"country,omitempty"`
	PostalCode           string   `protobuf:"bytes,6,opt,name=postalCode" json:"postalCode,omitempty"`
	Lat                  float32  `protobuf:"fixed32,7,opt,name=lat" json:"lat,omitempty"`
	Lon                  float32  `protobuf:"fixed32,8,opt,name=lon" json:"lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_profile_86ea0ebb379f6dd7, []int{3}
}
func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (dst *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(dst, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetStreetNumber() string {
	if m != nil {
		return m.StreetNumber
	}
	return ""
}

func (m *Address) GetStreetName() string {
	if m != nil {
		return m.StreetName
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Address) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *Address) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Address) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

type Image struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Default              bool     `protobuf:"varint,2,opt,name=default" json:"default,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_profile_86ea0ebb379f6dd7, []int{4}
}
func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (dst *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(dst, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Image) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

func init() {
	proto.RegisterType((*Request)(nil), "profile.Request")
	proto.RegisterType((*Result)(nil), "profile.Result")
	proto.RegisterType((*Pub)(nil), "profile.Pub")
	proto.RegisterType((*Address)(nil), "profile.Address")
	proto.RegisterType((*Image)(nil), "profile.Image")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProfileClient is the client API for Profile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileClient interface {
	GetProfiles(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error)
}

type profileClient struct {
	cc *grpc.ClientConn
}

func NewProfileClient(cc *grpc.ClientConn) ProfileClient {
	return &profileClient{cc}
}

func (c *profileClient) GetProfiles(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/profile.Profile/GetProfiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServer is the server API for Profile service.
type ProfileServer interface {
	GetProfiles(context.Context, *Request) (*Result, error)
}

func RegisterProfileServer(s *grpc.Server, srv ProfileServer) {
	s.RegisterService(&_Profile_serviceDesc, srv)
}

func _Profile_GetProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).GetProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.Profile/GetProfiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).GetProfiles(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Profile_serviceDesc = grpc.ServiceDesc{
	ServiceName: "profile.Profile",
	HandlerType: (*ProfileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfiles",
			Handler:    _Profile_GetProfiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/profile/proto/profile.proto",
}

func init() {
	proto.RegisterFile("services/profile/proto/profile.proto", fileDescriptor_profile_86ea0ebb379f6dd7)
}

var fileDescriptor_profile_86ea0ebb379f6dd7 = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xcd, 0x6a, 0xdc, 0x30,
	0x10, 0xc7, 0xf1, 0x7e, 0xd8, 0xc9, 0x6c, 0x48, 0xc3, 0x50, 0x8a, 0xe8, 0xa1, 0x18, 0x53, 0xca,
	0x92, 0x43, 0x5a, 0x36, 0xa7, 0xd2, 0x53, 0xe9, 0xa1, 0xe4, 0x52, 0x16, 0xbd, 0x81, 0x6c, 0x4d,
	0x5a, 0x81, 0xd6, 0x72, 0xf5, 0x51, 0xc8, 0xe3, 0xf5, 0x21, 0xfa, 0x3e, 0x45, 0x1f, 0xce, 0x3a,
	0x27, 0xcd, 0xff, 0x37, 0x23, 0xcd, 0xfc, 0xc5, 0xc0, 0x7b, 0x47, 0xf6, 0x8f, 0x1a, 0xc8, 0x7d,
	0x9c, 0xac, 0x79, 0x54, 0x9a, 0xe2, 0xe9, 0xcd, 0xac, 0xee, 0x92, 0xc2, 0xa6, 0xc8, 0xee, 0x33,
	0x34, 0x9c, 0x7e, 0x07, 0x72, 0x1e, 0xdf, 0x40, 0x3d, 0x85, 0xfe, 0x41, 0x3a, 0x56, 0xb5, 0xeb,
	0xfd, 0x25, 0x2f, 0x2a, 0x72, 0x6d, 0x06, 0xa1, 0x89, 0xad, 0xda, 0x2a, 0xf2, 0xac, 0xba, 0x5b,
	0xa8, 0x39, 0xb9, 0xa0, 0x3d, 0xb6, 0xb0, 0x99, 0x42, 0x9f, 0xef, 0xed, 0x0e, 0x57, 0x77, 0x73,
	0xaf, 0x63, 0xe8, 0x79, 0xca, 0x74, 0x7f, 0x2b, 0x58, 0x1f, 0x43, 0x8f, 0xd7, 0xb0, 0x52, 0x92,
	0x55, 0xe9, 0x9d, 0x95, 0x92, 0x88, 0xb0, 0x19, 0xc5, 0x69, 0x7e, 0x39, 0xc5, 0xd8, 0xc2, 0x6e,
	0xfa, 0x65, 0x46, 0xfa, 0x11, 0x4e, 0x3d, 0x59, 0xb6, 0x4e, 0xa9, 0x25, 0x8a, 0x15, 0x92, 0xdc,
	0x60, 0xd5, 0xe4, 0x95, 0x19, 0xd9, 0x26, 0x57, 0x2c, 0x10, 0xde, 0x42, 0x23, 0xa4, 0xb4, 0xe4,
	0x1c, 0xdb, 0xb6, 0xd5, 0x7e, 0x77, 0xb8, 0x79, 0x1e, 0xea, 0x6b, 0xe6, 0x7c, 0x2e, 0xc0, 0x0f,
	0x50, 0xab, 0x93, 0xf8, 0x49, 0x8e, 0xd5, 0x69, 0xfe, 0xeb, 0xe7, 0xd2, 0x87, 0x88, 0x79, 0xc9,
	0x76, 0xff, 0x2a, 0x68, 0xca, 0x65, 0xec, 0xe0, 0xca, 0x79, 0x4b, 0xe4, 0xcb, 0x90, 0xd9, 0xd1,
	0x0b, 0x86, 0xef, 0x00, 0x8a, 0x3e, 0x3b, 0x5c, 0x90, 0xe8, 0x7d, 0x50, 0xfe, 0xa9, 0x18, 0x4c,
	0x31, 0xbe, 0x86, 0xad, 0xf3, 0xc2, 0x53, 0xf1, 0x94, 0x05, 0x32, 0x68, 0x06, 0x13, 0x46, 0x6f,
	0x9f, 0x92, 0x9b, 0x4b, 0x3e, 0xcb, 0xd8, 0x63, 0x32, 0xce, 0x0b, 0xfd, 0xcd, 0x48, 0x62, 0x75,
	0xee, 0x71, 0x26, 0x78, 0x03, 0x6b, 0x2d, 0x3c, 0x6b, 0xda, 0x6a, 0xbf, 0xe2, 0x31, 0x4c, 0xc4,
	0x8c, 0xec, 0xa2, 0x10, 0x33, 0x76, 0xf7, 0xb0, 0x4d, 0x46, 0x63, 0x2a, 0x58, 0x5d, 0xbc, 0xc4,
	0x30, 0x36, 0x96, 0xf4, 0x28, 0x82, 0xf6, 0x69, 0xfe, 0x0b, 0x3e, 0xcb, 0xc3, 0x17, 0x68, 0x8e,
	0xf9, 0x97, 0xf0, 0x13, 0xec, 0xbe, 0x93, 0x2f, 0xca, 0xe1, 0xf9, 0xa7, 0xcb, 0x62, 0xbd, 0x7d,
	0xb5, 0x20, 0x71, 0x5f, 0xfa, 0x3a, 0x2d, 0xe1, 0xfd, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00,
	0xd7, 0x49, 0x32, 0xac, 0x02, 0x00, 0x00,
}
